---
- name: Wait for nextcloud to start
  ansible.builtin.uri:
    url: "https://{{ NEXTCLOUD_FQDN }}"
    method: GET
    follow_redirects: none
    status_code: [200,302]
    validate_certs: false
  register: http_result
  until: http_result.status == 302
  retries: 720 # 1 hour
  delay: 5 # seconds

- name: Set nextcloud maintenance window
  community.docker.docker_container_exec: 
    container: nextcloud
    command: "occ config:system:set maintenance_window_start --type=integer --value={{ NEXTCLOUD_MAINTENENCE_WINDOW_START }}"

- name: Mimetype migrations
  community.docker.docker_container_exec: 
    container: nextcloud
    command: "occ maintenance:repair --include-expensive"

- name: Created missing indices
  community.docker.docker_container_exec: 
    container: nextcloud
    command: "occ db:add-missing-indices"
    
- name: Install apps
  community.docker.docker_container_exec: 
    container: nextcloud
    command: "occ app:install {{ item }}"
  loop: NEXTCLOUD_APPS_INSTALL

- name: Enable apps
  community.docker.docker_container_exec: 
    container: nextcloud
    command: "occ app:enable {{ item }}"
  loop: NEXTCLOUD_APPS_ENABLE

- name: Disable apps
  community.docker.docker_container_exec: 
    container: nextcloud
    command: "occ app:disable {{ item }}"
  loop: NEXTCLOUD_APPS_DISABLE

- name: Remove apps
  community.docker.docker_container_exec: 
    container: nextcloud
    command: "occ app:remove {{ item }}"
  loop: NEXTCLOUD_APPS_REMOVE

- name: Update apps
  community.docker.docker_container_exec: 
    container: nextcloud
    command: "occ app:update --all"

# Other things to look into:
# Encryption: https://docs.nextcloud.com/server/latest/admin_manual/occ_command.html#encryption
# Antivirus: https://docs.nextcloud.com/server/latest/admin_manual/occ_command.html#antivirus-commands-label
# File cleanps: https://docs.nextcloud.com/server/latest/admin_manual/occ_command.html#file-operations
# Files scan: https://docs.nextcloud.com/server/latest/admin_manual/occ_command.html#scan
# Federation sync: https://docs.nextcloud.com/server/latest/admin_manual/occ_command.html#federation-sync
