---
  - name: Check if docker-compose file exists
    ansible.builtin.stat:
      path: "{{ NEXTCLOUD_PATH }}/docs/docker-compose.yml"
    register: nextcloud_stat_docker_compose_file

  - name: Docker Compose Start Apps
    community.docker.docker_compose_v2:
      project_src: "{{ NEXTCLOUD_PATH }}/docs"
      files: "docker-compose.yml"
      state: present
      pull: always
      project_name: nextcloud
    when: nextcloud_stat_docker_compose_file.stat.exists

